- name: Deploy to EC2 Server
  uses: appleboy/ssh-action@v1.2.2
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      cd /home/ubuntu/secure-authhentication-sysytem

      git fetch origin
      git reset --hard origin/main

      chmod +x scripts/deploy.sh
      ./scripts/deploy.sh